alias gst='git status'
alias gcm='git commit -m'
alias gmh='git log --follow -p --'
alias ll='ls -ls'
alias lh='ls -lsh'
alias la='ls -lsa'
alias gam='git status | grep "modified" | cut -d: -f2 | xargs -n 1 git add'
