blank_issues_enabled: true
contact_links:
  - name: Stack Overflow
    url: http://stackoverflow.com/questions/tagged/mysqltuner
    about: Please post usage questions or support issues on Stack Overflow using the 'mysqltuner' tag.
